### ISSUE TITLE
Trying to use the new STATUS tools...

### ISSUE THREAD

**Issue by irlnathan** [sr-gi/bitcoin_tools#4] opened 2017-11-20 18:09 UTC
I cloned the project, switched to the dev branch and then when I tried to execute: python run_analysis.py I received:

`ImportError: No module named bitcoin_tools.analysis.status.data_dump`

Probably a noob python issue.

**Comment by sr-gi** [comment] 2017-11-20 18:44
Have you placed the library ad a python library? (depends on your OS, but normally under `/usr/lib/python2.7/`) or included the library path as part of the python's path? (`export PYTHONPATH=$PYTHONPATH:/path_to_the_library`)?

**Comment by irlnathan** [comment] 2017-11-20 20:46
I set the path and now it's asking for a configuration file. Does that `sample_conf.py` file with the configuration information have to be in a particular place and renamed a particular name?

**Comment by sr-gi** [comment] 2017-11-20 21:04
You should copy it (or rename it) to conf.py, you can find it explained as a [comment](https://github.com/sr-gi/bitcoin_tools/blob/0a9468eb5462dca7b5370a64e15ae37e86e04e10/bitcoin_tools/sample_conf.py#L1) in sample_conf.py

**Comment by irlnathan** [comment] 2017-11-20 21:07
I was able to set the path, however, I ran into this problem when executing `python data_dump.py`:

```
~/code/bitcoin_tools/bitcoin_tools/analysis/status $ python data_dump.pyc

Traceback (most recent call last):

  File "/Users/(username)/code/bitcoin_tools/bitcoin_tools/analysis/status/data_dump.py", line 3, in <module>

    from bitcoin_tools.analysis.status.utils import check_multisig, get_min_input_size, roundup_rate, check_multisig_type

  File "/Users/niktesla/code/bitcoin_tools/bitcoin_tools/analysis/status/utils.py", line 1, in <module>
    import plyvel
ImportError: No module named plyvel
~/code/bitcoin_tools/bitcoin_tools/analysis/status $ python data_dump.py
Traceback (most recent call last):
  File "data_dump.py", line 3, in <module>
    from bitcoin_tools.analysis.status.utils import check_multisig, get_min_input_size, roundup_rate, check_multisig_type
  File "/Users/niktesla/code/bitcoin_tools/bitcoin_tools/analysis/status/utils.py", line 1, in <module>
    import plyvel
ImportError: No module named plyvel
```

I think this may be related to issues I had when installing requirements with pip?:

```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)

OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/ecdsa'
```

**Comment by sr-gi** [comment] 2017-11-20 22:42
Threw things here, first of all, data_dump.py is not meant to be called, notice that there is no main, you can use the functions on it by calling it with python will have no result.

Having said that, it seems that you are having some dependency problems, plyvel is not installed. You should run `pip2.7 install - r requirements.txt` to fulfill all the required dependencies. (notice that some dependencies also require non-python libraries, as is the case of plyvel, who need LevelDB to be installed. You can check the Readme.md at the root of the repository and github to check those requirements.)

Finally, you seem to be facing some permission problems. Since the last error shows a permission denied when trying to use the edcsa package for python. You should check that.

**Comment by irlnathan** [comment] 2017-11-20 22:59
I'm on it and thank you for your patience! This tool and the utxo paper is sooo needed to fully understand how utxo's function.

**Comment by sr-gi** [comment] 2017-11-20 23:36
I'm glad you find it useful, consider stating the repo if you like it.  Please close the issue once you're done.

**Comment by irlnathan** [comment] 2017-11-20 23:44
I resolved the rights and install issue but now I'm getting an error that should be simple, however, I'm not sure:

```
~/code/bitcoin_tools/bitcoin_tools $ python my.py

Traceback (most recent call last):
  File "my.py", line 8, in <module>
    parse_ldb(f_utxos)
  File "/Users/<username>/code/bitcoin_tools/bitcoin_tools/analysis/leveldb/utils.py", line 267, in parse_ldb
    fout = open(CFG.data_path + fout_name, 'w')

IOError: [Errno 2] No such file or directory: '~/code/bitcoin_tools/bitcoin_tools/data/utxos.txt'
~/code/bitcoin_tools/bitcoin_tools $ python my.py

Traceback (most recent call last):
  File "my.py", line 8, in <module>
    parse_ldb(f_utxos)
  File "/Users/<username>/code/bitcoin_tools/bitcoin_tools/analysis/leveldb/utils.py", line 267, in parse_ldb
    fout = open(CFG.data_path + fout_name, 'w')
IOError: [Errno 2] No such file or directory: '~/code/bitcoin_tools/bitcoin_tools/data/utxos.txt'
```

The my.py is the LevelDB UTXO dump example.  I definitely have a directory path identical and I've tried it with both an empty folder and a folder with an empty text file `utxo.txt`. Is there something very obvious I'm missing?

**Comment by sr-gi** [comment] 2017-11-21 03:06
`CFG.data_path` points to the data path folder you have configure in your `conf.py` (that should be a valid path). Seems that either you have specified a wrong path or the path you have specified does not exists.

**Comment by irlnathan** [comment] 2017-11-21 04:50
Was able to run everything now...`conf.py` doesn't like the use of the tilde `~`.

The `btc_core_path` should point to the root of where Bitcoin is installed right? (e.g. "/Users/<username>/Library/Application Support/Bitcoin")

The `bitcoin_tools_dir` should point to where this repo was installed right? (e.g. "/Users/<username>/code/bitcoin_tools")

I was able to execute `my.py` which created two files `utxos.txt` and `parsed_utxos.txt`, however, both were empty. Maybe I have my paths to the wrong folders?

For posterity in case this might help someone else, I was able to get through the other issues by making sure:

- `export PYTHONPATH=$PYTHONPATH:~/code/bitcoin_tools`
- Installing `pip` with homebrew and using it to first install the requirements: `pip install -r requirements.txt`
- Then using `pip` to install the `plyvel` and `leveldb` libraries separately
- Finally, got over the permissions issue by using the `--user` flag (e.g. `pip install leveldb --user`)

**Comment by sr-gi** [comment] 2017-11-21 07:57
`btc_core_dir` should point to the Bitcoin core data folder (normally `/home/your_user/. bitcoin` in Linux systems). 

`bitcoin_tools_dir` should point to a a folder in which the data generated by the library will be stored (that's on you, I'd recommend `/home/your_user/bitcoin_tools`.

Notice that in your both examples you have an extra `/` after `Users`.

If the files are empty you're probably pointing to the wrong folders. Get sure that the `btc_core_dir` points where the chainstate is placed. 

Finally, notice that all this is commented in the sample_conf.py file.

**Comment by irlnathan** [comment] 2017-11-21 20:41
> Finally, notice that all this is commented in the sample_conf.py file.
I read the comments in `sample_conf.py` and was very confused by them. For example, on OSX the location is not "usually" `home_dir + ".bitcoin"`. It's `~/Library/Application Support/Bitcoin/`. 

> Notice that in your both examples you have an extra / after Users.
Not sure how those got added but I've corrected them thanks.

 > If the files are empty you're probably pointing to the wrong folders. Get sure that the btc_core_dir points where the chainstate is placed.
`btc_core_path` is to the root of the Bitcoin folder. Above you mentioned chainstate which is in Bitcoin/chainstate. So which is it, the root or chainstate? BTW if I put `Bitcoin/chainstate` in the `btc_core_path` I get an error so I'm assuming it's just the root of core.

When I execute the example from the repo:
```
from bitcoin_tools.analysis.leveldb.data_dump import utxo_dump
from bitcoin_tools.analysis.leveldb.utils import parse_ldb

f_utxos = "utxos.txt"
f_parsed_utxos = "parsed_utxos.txt"

# Parse all the data in the chainstate.
parse_ldb(f_utxos)
# Parses transactions and utxos from the dumped data.
utxo_dump(f_utxos, f_parsed_utxos)

# Data is stored in f_utxos and f_parsed_utxos files respectivaly
```
The `utxos.txt` and `parsed_utxos.txt` are empty. The Bitcoin/chainstate folder is fully updated so not sure why I'm getting empty files.

There's a space in  the path "/Application Support/Bitcoin" (not sure if that makes a difference. Is there any logging that I can do to determine where things are breaking?

Minor FYI: `requeriments.txt` is  misspelled.

**Comment by sr-gi** [comment] 2017-11-21 20:50
Thanks for the FYI, haven't noticed it.

Regarding the empty files, which version of the bitcoin core are you using?

**Comment by irlnathan** [comment] 2017-11-21 21:15
0.15.0.1

**Comment by sr-gi** [comment] 2017-11-21 21:41
Is it a fresh 0.15.1, or have you updated it from a previous 0.14.x or earlier version?

**Comment by irlnathan** [comment] 2017-11-21 21:43
fresh install

**Comment by sr-gi** [comment] 2017-11-21 23:22
Let's try something. Pull dev branch to the last commit, and try to execute the following code. At lest we will check if it's a version problem or a config problem.

```
from bitcoin_tools.analysis.status.utils import get_utxo

tx_id = '000006eea2b069136698e059f0b1c95730814e68244c5d76da69de3e9e5b8f81'
index = 0

for version in [0.14, 0.15]:
    r = get_utxo(tx_id, index, version=version)
    print "Right version " + str(version) if r else "Wrong version " + str(version)
```

**Comment by sr-gi** [comment] 2017-11-22 00:11
What makes me think, are you currently using master or dev branch?

**Comment by irlnathan** [comment] 2017-11-22 15:44
The first time I executed your script I received an error that I was missing the `ujson` module, so I installed it with `pip` (using the `--user` flag). The second time I executed the script I received the following:

```
Wrong version 0.14
Right version 0.15
```

For the heck of it I ran the script:
```
from bitcoin_tools.analysis.leveldb.data_dump import utxo_dump
from bitcoin_tools.analysis.leveldb.utils import parse_ldb

f_utxos = "utxos.txt"
f_parsed_utxos = "parsed_utxos.txt"

# Parse all the data in the chainstate.
parse_ldb(f_utxos)
# Parses transactions and utxos from the dumped data.
utxo_dump(f_utxos, f_parsed_utxos)

# Data is stored in f_utxos and f_parsed_utxos files respectivaly
```

And received the error: `ImportError: No module named leveldb.data_dump`

Is `leveldb.data_dump` a different module than `leveldb`?

**Comment by sr-gi** [comment] 2017-11-22 16:09
Ok, I'm quite sure to know what's happening. You're running the code under master branch which contains a simple and old version of STATUS. That version only works with Bitcoin core's chainstate for versions under 0.15. 

In order to use the most recent version of the tool (the one that is referenced in the paper) you should checkout to the dev branch of the git repository ( `git checkout dev`). Then if you try to use the updated example for parsing the LevelDB (you will find it in the Readme.md of the dev branch, don't use the one you're trying to run now), it should work.

**Comment by irlnathan** [comment] 2017-11-22 18:14
Success...I have the two 15GB and 16GB files. Many many thanks!

Here's an example of an entry from both files:
```
`parsed_utxos.txt`

{
  "index":0,
  "loss_making":6420,
  "non_std_type":"std",
  "out_type":0,
  "utxo_data_len":20,
  "register_len":36,
  "tx_id":"000000dcf3713a29f3da53dbde07ea93ace52a4393ba9a009d8ac17c853c18e5",
  "amount":942800,
  "tx_height":491516,
  "dust":2140, 
  "data":"7b8268c6115b707d17cccfdf9be636467a80f9e4"
}

`utxos.txt`

{
  "key":"000000dcf3713a29f3da53dbde07ea93ace52a4393ba9a009d8ac17c853c18e500",
  "value":
  {
    "coinbase":0,
    "height":491516,
    "index":0,
    "outs":[
      {
        "amount":942800,
        "data":"7b8268c6115b707d17cccfdf9be636467a80f9e4",
        "out_type":0
      }
    ],
    "tx_id":"000000dcf3713a29f3da53dbde07ea93ace52a4393ba9a009d8ac17c853c18e5"}
  }
```

Is the `tx_id` in different format than one you'd fine on a blockexplorer?

**Comment by sr-gi** [comment] 2017-11-22 19:53
Yes, `tx_id` is displayed in little endian, that is how it is encoded on the chainstate. Block explorers usually display it in `big endian`.

You can change the endianness of any hex encoded string by using the `change_endianness` function under `bitcoin_tools.utils`

**Comment by irlnathan** [comment] 2017-11-22 21:04
Last question :). In the paper you talk about some of the properties of the chain state (v14 and v15) versus some of the meta data you're adding, however, is there complete documentation about all of the properties that are contained in the native chainstate (e.g. leveldb database) compared to the properties in the files you create?

**Comment by sr-gi** [comment] 2017-11-22 21:20
No, however, the data you get after performing `parse_ldb` is the result of just decoding the information contained in the chainstate, with no meta-data added. The meta-data is added once you perform the `utxo_dump` or the `tx_dump` using the decoded data.

You can find what each property is in the functions documentation and comments.

**Comment by sr-gi** [comment] 2017-11-23 14:43
@irlnathan let me know if the issue is solved to close it.

**Closed** 2017-11-24 18:25 UTC

**Comment by irlnathan** [comment] 2017-11-25 03:12
Apologies for the Thanksgiving delay :), everything was answered many thanks!

**Comment by agoora** [comment] 2017-12-13 20:48
Hi irlnathan or Sergi,

Please help me with this error:
For a few days I'm trying unsuccessfully to run this script without any results ...
I mention that I read and did all the steps in the documentation!

test@bf:~/bitcoin_tools/bitcoin_tools$ python dev.py
Traceback (most recent call last):
  File "dev.py", line 1, in <module>
    from bitcoin_tools.analysis.status.data_dump import utxo_dump
ImportError: No module named bitcoin_tools.analysis.status.data_dump
test@bf:~/bitcoin_tools/bitcoin_tools$

**Comment by sr-gi** [comment] 2017-12-13 23:30
@agoora seem that you are in main branch, and not in dev branch, can you run git branch and check it? You should checkout to dev branch before trying to use the code.
